### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by underscore-ex** [tw-yshuang/Git_SSH-Account_Switch#3]
Got this error

```bash
❯ ./setup.sh
zsh: permission denied: ./setup.sh

~/repos/Git_SSH-Account_Switch-main : sudo chmod +x setup.sh
Password:

~/repos/Git_SSH-Account_Switch-main : ./setup.sh
/Users/xyz/.git-acc: line 4: syntax error near unexpected token `('
/Users/xyz/.git-acc: line 4: `  local function Echo_Color(){'
Done!! Now can use! Enjoy~~~
```

**Comment by tw-yshuang** [comment]
Hi, I think the problem is because `./setup.sh` needs to be executed by `bash`, so you can follow the command that I mentioned on README.md:
```shell
$ bash ./setup.sh
``` 
I hope it can help you.

**Comment by Ojasv-Singh-Zeotap** [comment]
![image](https://user-images.githubusercontent.com/77407526/168834906-9a6dacf9-dced-4ccb-9187-54eef688fe3c.png)

<img width="539" alt="image" src="https://user-images.githubusercontent.com/77407526/168839435-f08afbc0-8fac-439b-a394-6b70ad39669e.png">

Getting this error even with bash @tw-yshuang

**Comment by tw-yshuang** [comment]
I will fix this issue, thank you!

**Comment by tw-yshuang** [comment]
I fixed this issue and released [v1.2.0](https://github.com/tw-yshuang/Git_SSH-Account_Switch/releases/tag/ver_1.2.0), go to check it out!!

**Comment by wcarrasc** [comment]
Hello! I cloned repo and downloaded 1.2.0 and having the same error with both ways:

`bash ./setup.sh 
You have already added git-acc config in /Users/walthercarrasco/.zshrc !!
Only update your git-acc!
/Users/walthercarrasco/.git-acc: line 4: syntax error near unexpected token `('
/Users/walthercarrasco/.git-acc: line 4: `  local function Echo_Color(){'
Done!! Now can use! Enjoy~~~`

**Comment by tw-yshuang** [comment]
This error is different from the previous issue, in the `setup.sh`, I design a mechanism that can detect whether the current machine has been installed or not, if it's installed, then this script will only update `git-acc`, and this error is because I'm using `bash` to execute `source git-acc` in the `setup.sh` (it is a bad idea, ha!), and `bash` can not recognize `zsh` syntax, but it is not causing any problem if you reopen another terminal, this is a good problem to mention it, I will turn `setup.sh` to `zsh` when I have free time, thanks!
