### ISSUE TITLE
How to uninstall/remove properly or fix this issue?

### ISSUE THREAD

**Issue by Radiac93** [tw-yshuang/Git_SSH-Account_Switch#5]
When I start a terminal I get a ".git-acc:259: command not found: complete".
It also gave me issues with my conda installation.

I'm assuming I can re-install compgen to fix this, but I'd like to understand why it's happening.

```zsh
/Users/myusername/.git-acc:259: command not found: complete
(base) myusername@My-MacBook-Pro ~ % conda activate bivscraper
local:15: command not found: compgen
local:17: = not found
```

MacOs version 12.5.1 (21G83)
M1 Chip

**Comment by tw-yshuang** [comment]
This tool is provided for `zsh` to use, you can check by following the command down below:
``` zsh
echo $SHELL
```
Sorry, I'm not using `conda` to manage my python environment, but I assume that in the `conda` installation, it uses `bash` as the default shell to execute it, it shows the error because `bash` & `zsh` has some different syntax & command, for me, `zsh` is a more powerful option.

If you are interested, you can use `pyenv` & `pipenv` to manage the python version & virtual environment with those two great tools, if you are not familiar, you can visit this post below that I write with undergraduate research student:
https://medium.com/ntust-aivc/how-to-install-pyenv-pipenv-in-ubuntu-and-use-multiple-versions-of-python-and-its-suites-3514099a6e05

**Comment by Radiac93** [comment]
The environment is zsh, when I activate a conda environment the shell is still zsh, so I don't think that's the issue.
I use conda as this is what my team uses.

Two questions:

1. How can I completely uninstall this tool?
2. What logs/information can I provide to pinpoint this bug and help solve it?

I really like the simplicity of your tool and would love to be able to continue using it.

**Comment by tw-yshuang** [comment]
Thanks for appreciating this tool~
For the first question, I create a script for it in [507a6d8](https://github.com/tw-yshuang/Git_SSH-Account_Switch/commit/507a6d8ea6982203bc6e476a7a7670bb557c26db) uninstall.sh.

For the second question, sorry, I do not know what the core problem is, `complete` and `compgen` are the build-in syntax for `zsh`, so I have no idea why it can not work perfectly on `conda` if you are using `zsh`.

**Comment by Radiac93** [comment]
Thanks for the quick reply!

From what I can see [507a6d8](https://github.com/tw-yshuang/Git_SSH-Account_Switch/commit/507a6d8ea6982203bc6e476a7a7670bb557c26db) is an update of your "setup.sh" ?
I can't seem to find the referenced "uninstall.sh" script in the repo, am I overlooking something?

**Comment by tw-yshuang** [comment]
Sorry, I gave the wrong link, go to check it out [uninstall.sh](https://github.com/tw-yshuang/Git_SSH-Account_Switch/blob/5310e607fa58219e464545a454c5328cc10984d9/uninstall.sh)!!
